# Generated by Django 5.2.7 on 2025-10-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_epargne', to='gestion.adherent', verbose_name='Adhérent')),
            ],
        ),
        migrations.CreateModel(
            name='OperationEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('INTERET', 'Intérêt')], default='DEPOT', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='epargne.compteepargne')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
