# Generated by Django 5.2.7 on 2025-10-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retraites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondsRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fonds de Retraite',
            },
        ),
        migrations.CreateModel(
            name='PaiementRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('demande', models.ForeignKey(limit_choices_to={'statut': 'APPROUVEE'}, on_delete=django.db.models.deletion.PROTECT, to='retraites.demanderetraite')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
