# Generated by Django 5.2.7 on 2025-10-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_retraite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant demandé')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=10)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retraite', to='gestion.adherent', verbose_name='Adhérent')),
            ],
            options={
                'verbose_name': 'Demande de Retraite',
                'verbose_name_plural': 'Demandes de Retraite',
                'ordering': ['-date_demande'],
            },
        ),
    ]
