# Generated by Django 5.2.7 on 2025-10-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_cotisations', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_retraites', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_epargnes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fichier_rapport', models.FileField(blank=True, null=True, upload_to='rapports/%Y/%m/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
