name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Installer Docker et Docker Compose si non installés
            if ! command -v docker &> /dev/null; then
              sudo apt update -y
              sudo apt install -y docker.io
            fi

            if ! docker compose version &> /dev/null; then
              sudo apt install -y docker-compose-plugin
            fi

            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        
            if [ ! -d "caisse_retrait_deploy" ]; then
              git clone git@github.com:AssemienDev/caisse_retrait_deploy.git
            fi
            cd caisse_retrait_deploy
            git pull origin main

            # Créer le fichier .env proprement
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

            # Reconstruire et relancer les conteneurs
            docker compose down
            docker compose up -d --build

            # Nettoyer les images inutilisées
            docker image prune -af
